- src/ansible/roles/ipa/tasks/main.yml
This removes the need to do this step explictily.
This also fix the following error on Fedora 34:
```
fatal: [ipa]: FAILED! => changed=true
cmd: |-
kinit admin
ipa trust-add samba.test --admin Administrator --password
delta: '0:00:01.131665'
end: '2022-04-12 02:57:30.557983'
msg: non-zero return code
rc: 1
start: '2022-04-12 02:57:29.426318'
stderr: 'ipa: ERROR: CIFS server communication error: code "3221225564", message "An attempt has been made to operate on an impersonation token by a thread that is not currently impersonating a client." (both may be "None")'
stderr_lines: <omitted>
stdout: 'Password for admin@IPA.TEST: '
stdout_lines: <omitted>
```
This error could be also fixed by restarting krb5kdc after
ipa-adtrust-install. But avoiding this step completely is better.
> ansible: add --setup-adtrust to ipa installation

- readme.md
The list of unavailable services should be included in quotation marks.
> doc: improve UNAVAILABLE explanation

- src/ansible/roles/common/tasks/main.yml
The authorized keys contained private instead of public key breaking the ssh authentication to the containers.
> Fix containers .ssh/authorized_keys

- src/ansible/roles/samba/files/sudo.class.ldif
sudoRole objects are now readable by Authenticated Users.
> samba: fix ACL on sudoRole object class

- src/ansible/roles/ipa/tasks/main.yml
By removing these maps we get empty initial state consistent to what
we have in other providers. This will simplify testing of autofs using
parametrized topology.
> ipa: remove auto.master and auto.direct autofs maps

- docker-compose.yml
ssh connections are failing due to:
fatal: chroot("/usr/share/empty.sshd"): Operation not permitted [preauth]
Adding SYS_CHROOT capability fixes the problem. This solution is based on https://access.redhat.com/solutions/3626531
Unfortunately I don't have time to investigate the issue more profoundly. I don't know why the problem appeared now and it was working correctly before. If you don't like the solution, take this patch as a problem report and provide a better fix.
> compose: add SYS_CHROOT capability

- docker-compose.yml
Fixes the error:
ERROR: Network "sssd-ci" needs to be recreated - IPAM option "driver" has changed
> Network: Fix iPAM option validation error

- Makefile
- docker-compose.passkey.yml
- docker-compose.yml
- src/ansible/roles/client/files/random.c
- src/ansible/roles/client/tasks/main.yml
- src/ansible/roles/facts/tasks/CentOS.yml
- src/ansible/roles/facts/tasks/CentOS8.yml
- src/ansible/roles/facts/tasks/CentOS9.yml
- src/ansible/roles/facts/tasks/Debian.yml
- src/ansible/roles/facts/tasks/Fedora.yml
- src/ansible/roles/facts/tasks/RedHat.yml
- src/ansible/roles/facts/tasks/Ubuntu.yml
- src/ansible/roles/packages/tasks/Fedora.yml
- src/ansible/roles/packages/tasks/Ubuntu.yml
The following packages, capabilities and binaries are needed to perform the passkey testing in an automated way.
> Add passkey testing support

- Makefile
Prevent recreating containers unexpectedly.
> Set --no-recreate docker compose up option

- .github/workflows/actions.yml
- actions/setup/action.yml
There is a race condition in podman that was fixed in v4 which is
not yet available in current ubuntu github runners.
```
ERROR: for client  Cannot start service client: error configuring network namespace for container 8d66f2cf911f87e75a2f54759808c68be3ef13088d427af04ecfe4392f025180: error adding pod client_client to CNI network "sssd-ci": running [/usr
```
This change should mitigate that.
> actions: retry start of containers upon failure

- src/ansible/roles/packages/tasks/Debian.yml
- src/ansible/roles/packages/tasks/Fedora.yml
- src/ansible/roles/packages/tasks/Ubuntu.yml
https://github.com/SSSD/sssd/commit/c6db359fa8b75ed0d03b7211c588e8c317d80c26 added a new dependency for the multihost tests to the chattr command, which is provided by the e2fsprogs package.
> fedora: install e2fsprogs

- src/ansible/roles/packages/tasks/Debian.yml
- src/ansible/roles/packages/tasks/Fedora.yml
- src/ansible/roles/packages/tasks/Ubuntu.yml
9e2203a6d3d1b20cd3347a621574f2b4da52bdb9 installed it in the client image only, but it is needed in all images.
> packages: install e2fsprogs in base_ground

- actions/setup/action.yml
Older podman has a race condition which sometimes ends up in failure
when starting containers so we added a retry to mitigate it. However,
when we retry it, it refuses to retry and trows "network must be
recreated" which is also an issue with older podman. This change
mitigates that.
> actions: put down containers before starting them to allow retry

- docker-compose.yml
- src/ansible/playbook_image_service.yml
- src/ansible/roles/firewall/tasks/main.yml
- src/ansible/roles/packages/tasks/Debian.yml
- src/ansible/roles/packages/tasks/Fedora.yml
- src/ansible/roles/packages/tasks/Ubuntu.yml
We set the default zone to trusted so all incomming communication is
allowed. We can then just block specific ports in CI to simulate
unreachable servers with rich rules, for example:
```
firewall-cmd --add-rich-rule 'rule service name=ldap reject'
```
> ansible: add firewalld

- actions/setup/action.yml
There is a regression in podman that fails to create networks. The
workaround is to avoid update of the podman package. We can skip
the installation since both podman and docker-compose are available
in the base image.
See: https://github.com/actions/runner-images/issues/7753
> action: do not install packages in setup

- src/ansible/roles/passkey/files/random.c
Fedora started providing arc4random_buf(), so libfido2 switched and
started using this random generator provider. I'm adding a simple mock
for this function so that QE can continue their work.
> passkey: add arc4random_buf() to random.so

- src/ansible/roles/ipa/tasks/main.yml
When installing in openstack the server pulls link-local ipv6 address. This breaks the installation so we need to define the address implicitly to prevent that.
> Add ip address definition for ipa server installation.

- src/ansible/roles/client/tasks/main.yml
We need krb5.conf  with rdns = false for realm join to work properly in environment where reverse dns records are different that internal names.
> provision: Add krb5.conf for realm join

- src/ansible/roles/packages/tasks/RedHat8.yml
RHEL need epel-release specified with url as it is not part of normally available packages:
2023-10-06T10:51:00 TASK [packages : Install EPEL repository] **************************************
2023-10-06T10:51:01 fatal: [dns.test]: FAILED! => changed=false 
2023-10-06T10:51:01   failures:
2023-10-06T10:51:01   - No package epel-release available.
2023-10-06T10:51:01   msg: Failed to install some of the specified packages
2023-10-06T10:51:01   rc: 1
2023-10-06T10:51:01   results: []
...
With fix:
2023-10-06T12:49:39 TASK [packages : Install EPEL repository] **************************************
2023-10-06T12:49:41 changed: [dns.test]
2023-10-06T12:49:42 changed: [master.ldap.test]
2023-10-06T12:49:42 changed: [client.test]
2023-10-06T12:49:42 changed: [kdc.test]
2023-10-06T12:49:42 …
> packages: install epel-release from url since the package is not available in rhel

- src/ansible/playbook_image_service.yml
- src/ansible/roles/no_nscd/tasks/main.yml
- src/ansible/roles/packages/tasks/Debian.yml
- src/ansible/roles/packages/tasks/Ubuntu.yml
On some platforms nscd might be pulled in and started via dependencies.
Since running SSSD together with nscd is not supported it should be
disabled if present.
> build: disable nscd if present

- actions/setup/action.yml
I'm not sure what is the exact root cause but this fixes an issue where `systemctl enable --now podman.socket` fails during container setup.
~~~
+ sudo systemctl enable --now podman.socket
Job failed. See "journalctl -xe" for details.
Nov 07 16:01:19 fv-az1153-970 sudo[3267]:   runner : *** ; USER=root ; COMMAND=/usr/bin/systemctl enable --now podman.socket
Nov 07 16:01:19 fv-az1153-970 systemd[1]: podman.socket: Socket service podman.service already active, refusing.
Nov 07 16:01:19 fv-az1153-970 systemd[1]: Failed to listen on Podman API Socket.
~~~
This leads to `docker-compose` failing as the service is [not started properly](https://github.com/docker/compose/issues/7896)
~~~
make: Entering directory '/home/runner/work/sssd/sssd/sssd-ci-containers'
docker-compose -f docker-compose.yml …
> ci: restart podman socket during setup

- src/ansible/playbook_vm.yml
Allow overriding trust between IPA and samba and IPA and AD.
> ci: Allow overriding trust

- src/ansible/group_vars/all
- src/ansible/playbook_vm.yml
- src/ansible/roles/ad/defaults/main.yml
- src/ansible/roles/ad/tasks/dns.yml
- src/ansible/roles/ad/tasks/install.yml
- src/ansible/roles/ad/tasks/main.yml
- src/ansible/roles/ad/tasks/schema.yml
- src/ansible/roles/client/tasks/enroll_AD.yml
- src/ansible/roles/client/tasks/enroll_IPA.yml
- src/ansible/roles/client/tasks/enroll_samba.yml
- src/ansible/roles/client/tasks/main.yml
- src/ansible/roles/client/templates/krb5.conf
- src/ansible/roles/client/templates/sssd.conf
- src/ansible/roles/dns/tasks/main.yml
- src/ansible/roles/dns/templates/etc.dnsmasq.conf.j2
- src/ansible/roles/ipa/tasks/main.yml
- src/ansible/roles/samba/tasks/main.yml
- src/ansible/roles/samba/templates/sudo.attrs.ldif.j2
- src/ansible/roles/samba/templates/sudo.class.ldif.j2
Improve dns role to be less reliant on idmci and work with machines more dynamically.
Update ipa and client roles to handle better missing backends.
Change ad role to allow hostname/domain randomization. 
Remove partially service.XXX style config in a favour of dynamic configuration. 
Refactor joining domains (IPA, AD samba) to standalone files.
> ci: Improve dynamic machine setup especially for randomized AD

- .github/actions/install-dependencies/action.yml
- src/build.sh
To workaround [1] in Github actions environment. Github Actions Runners
do not yet have up to date podman version that contains this fix.
[1] https://github.com/containers/podman/issues/21012
> build: build base images in unconfined mode

- src/ansible/roles/packages/tasks/Fedora.yml
To allow man pages installation. This is to enable proper feature detection that rely on man pages content.
> Fedora: remove 'nodocs' from dnf.conf::tsflags

- data/configs/dnsmasq.conf
- src/ansible/roles/dns/templates/etc.dnsmasq.conf.j2
- src/ansible/roles/ipa/tasks/main.yml
In order to test sss_ssh_knownhosts command, we need to have
a valid reverse zone so we can add a host with known certificate
that can be resolved though hostname and reverse lookup of IP address.
> ipa: manage reverse zone for artificial hosts

- src/ansible/roles/samba/tasks/main.yml
7 should be enough for daemons, and command line tools don't need high verbosity at all (otherwise mh.log gets spammed)
> Samba: reduce default log level

- src/ansible/playbook_image_service.yml
- src/ansible/playbook_vm.yml
There is no point in switching off ldap and ipa on VMs.
> provision: Make cleanup skipped again on VMs.

- src/ansible/roles/packages/tasks/Fedora.yml
There are chroots in copr from rhel-10 or epel-10 yet so we will use c10s one for now.
> packages: Use centos-stream-10 chroot for c10s and rhel-10

- src/ansible/playbook_vm.yml
- src/ansible/roles/client/templates/krb5.conf
- src/ansible/roles/packages/tasks/Fedora.yml
- src/ansible/roles/samba/tasks/main.yml
Currently, we provide machines that are already fully setup with the
client enrolled into all domains and trusts established. This is no
longer necessary. With this patch, we will enroll into the domains
using per-topology setup if needed.
This applies only to downstream CI. Containers are still fully provisioned.
Please note that this needs to be closed together with changes to other repositories:
* https://github.com/SSSD/sssd/pull/7349
* https://github.com/next-actions/pytest-mh/pull/54
* https://github.com/next-actions/pytest-mh/pull/54
> provision: do not join domains automatically in Idm CI

- src/ansible/roles/packages/tasks/Debian.yml
- src/ansible/roles/packages/tasks/Fedora.yml
- src/ansible/roles/packages/tasks/Ubuntu.yml
It's not used to build SSSD since
https://github.com/SSSD/sssd/commit/10069b1d39e671b7502c5211883c94ceaa91aebb
> Remove http-parser dependency

- .github/actions/install-dependencies/action.yml
- src/ansible/roles/packages/tasks/Fedora.yml
- src/build.sh
Work around for: 
- https://github.com/ansible/ansible/issues/83373
- https://github.com/rpm-software-management/dnf5/issues/846
- https://github.com/rpm-software-management/dnf5/issues/1537
"Fix" for:
- https://github.com/rpm-software-management/dnf5/issues/1528
> ci: Fix dnf5 issues and add passlib

- src/ansible/roles/packages/tasks/Fedora.yml
While installing sssd and dependancy add sssd-kcm
explicitly as its not downloading with 'sssd-*'
> Package: Add sssd-kcm explicitly

- docker-compose.yml
and IPA containers.
Currently only 'CAP_DAC_READ_SEARCH' was missing, so probably other were added by default. But it is more clear to list everything explicitly.
> Explicitly allow all capabilities required by SSSD in client

- .github/actions/install-dependencies/action.yml
- .github/workflows/build.yml
- src/ansible/roles/packages/tasks/CentOS8.yml
- src/ansible/roles/packages/tasks/Fedora.yml
- src/ansible/roles/packages/templates/repo
- src/build.sh
- The original centos mirrors no longer work so we need to switch to vault repos instead.
- ansible-core-2.17 is not compatible with CentOS 8 so we need to use older 2.16 version.
- C8s Buildroot is not available atm. in koji so we in non-mandatory repo.
- Crb (powertools) repo is needed for some packages from client-devel
- We need to make sure seliinux-poilicy-targeted needed by smartcards is installed on c8s.
> ci: Switch c8s repos to vault

- src/ansible/playbook_image_service.yml
- src/ansible/roles/ssh_server/tasks/main.yml
Run roles against host groups instead of hostnames as a preparation for extending the topologies.
Make sure ssh is not broken for ad-hoc added machines referencing non-existent host keys.
> Match roles against host groups, tweak ssh server.

- src/ansible/roles/packages/tasks/Debian.yml
- src/ansible/roles/packages/tasks/Fedora.yml
- src/ansible/roles/packages/tasks/Ubuntu.yml
Strings command is used in feature detection on client but binutils providing it are by default missing in containers.
> provision: Add binutils to have strings available on client

- src/ansible/roles/dns/tasks/main.yml
- src/ansible/roles/samba/tasks/main.yml
This fixes dns installation on dns machine and samba installation on fedora 40 in idmci by removing systemd-resolved pieces in the correct order.
> dns: Tweak dns role to work better with systemd-resolved

- .github/actions/install-dependencies/action.yml
The original link is no longer available.
> ci: fix link for package to workaround networking issue

- actions/setup/action.yml
'sudo' calls 'unix_chkpwd' and this fails with
```
openat(AT_FDCWD</>, "/etc/shadow", O_RDONLY|O_CLOEXEC) = -1 EACCES
```
for unclear reason (CAP_DAC_* are granted)
Let root read /etc/shadow without capabilities as a work around.
> Workaround failing sudo

- src/ansible/roles/packages/tasks/Fedora.yml
We need to disable beaker tasks repo for sssd package installation to prevent stray package inclusion.
Rsync is missing from RHEL 10.0 aarch64 and needs to be explicitly installed for common role.
> Update for multiarch testing

- src/ansible/roles/dns/templates/etc.dnsmasq.conf.j2
The record for reverse zone was hardcoded in dns config instead of being added only when needed.
> dns: Make ipa reverse zones inclusion in dns config optional

- src/ansible/roles/client/templates/sssd.conf
`config_file_version` and `user` options aren't valid anymore.
> Update sssd.conf template

- src/Containerfile
- src/ansible/inventory.yml
```
381aac5 (Pavel Březina, 2 minutes ago)
provision: fix AD credentials in inventory
For some reason, `.\Administrator` is no longer working. This format should
allowed both plain Administrator and Administrator from AD domain to login
with the same inventory file, but authentication just fails with it now.
On the other hand, while this was required before, it does not seem to be
required now as the provisioning works without the dot.
986808b (Pavel Březina, 4 minutes ago)
vagrant: fix vagrant build
The apt changed the location and contents of sources configuration file.
Ubuntu no longer ships vagrant therefore it was not possible to install its
build dependencies with build-dep command.
Now we build vagrant on debian instead of ubuntu, with required changes.
```
> fix vagrant build and AD provisioning

- src/ansible/filter_plugins/distro.py
- src/ansible/roles/client/tasks/enroll_AD.yml
- src/ansible/roles/client/tasks/enroll_IPA.yml
- src/ansible/roles/client/tasks/enroll_samba.yml
- src/ansible/roles/client/tasks/main.yml
- src/ansible/roles/client/templates/sssd.conf
- src/ansible/roles/common/tasks/main.yml
- src/ansible/roles/firewall/tasks/main.yml
- src/ansible/roles/ipa/tasks/main.yml
- src/ansible/roles/keycloak/tasks/main.yml
- src/ansible/roles/ldap/tasks/main.yml
- src/ansible/roles/packages/tasks/RedHat-rpm-ostree.yml
- src/ansible/roles/packages/tasks/main.yml
- src/ansible/roles/samba/tasks/main.yml
- src/ansible/roles/ssh_server/tasks/main.yml
- src/ansible/roles/ssh_server/templates/sshd.conf
- src/ansible/roles/virtsmartcard/tasks/main.yml
RHEL image mode does not allow to install packages using dnf nor yum.
We need to use rpm-ostree to install them in the overlay.
This change installs a limited number of packages needed 
on the client as test dependencies.
Move /data and /enrollment under /var as root is read only.
Skip smart-card setup when on rpm-ostree.
> provision: Install client packages to overlay in image mode

- src/ansible/playbook_image_service.yml
- src/ansible/roles/ipasmartcard/defaults/main.yml
- src/ansible/roles/ipasmartcard/tasks/main.yml
Configure IPA server and client using ipa-advise scripts.
Currently there is an issue with IPA WebUI OCSP verifications when the IPA server is configured using an external CA.  To work around this we disable OCSP checking in /etc/httpd/conf.d/ssl.conf on the IPA server.
> ipasmartcard: new role for IPA smart card support

- src/ansible/group_vars/all
- src/ansible/roles/dns/templates/etc.dnsmasq.conf.j2
- src/ansible/roles/facts/tasks/CentOS10.yml
- src/ansible/roles/ipa/tasks/main.yml
- src/ansible/roles/ipasmartcard/tasks/main.yml
When configured using playbook_vm.yaml, the client is not enrolled in IPA by default.  This causes the ipasmartcard role to currently fail to find the IPA kerberos keytab needed.   The client side setup can be skipped in the case where the system is not enrolled to IPA.
> Skip ipasmartcard on client if not joined to IPA

- src/build.sh
Adding ANSIBLE_OPTS to the ansible-playbook command that runs
playbook_image_base.yaml in build.sh.   This is needed to set specific
variables needed during the base playbook like virt_smartcard that is
used to install packages specific to smart card tests.
> Add ANSIBLE_OPTS when running playbook_image_base

- src/ansible/group_vars/all
In order to enable smart card testing in upstream PRCI, we need virt_smartcard enabled in the client container stored upstream.
> Enable virt_smartcard for smart card testing

- src/ansible/playbook_vm.yml
- src/ansible/roles/facts/tasks/CentOS10.yml
virt_smartcard was explicitly disabled for Centos 10 setup.   This needs
to be enabled so that the centos10 system tests can run smart card tests
in PR-CI.   Removing this from the Centos10 specific facts task file.
Also fix a virt_smartcard typo in playbook_vm.yml
> Enable virt_smartcard for centos10
